name: abc
on:
  push

jobs:
  fuzzy:
    name: fuzzy
    runs-on: ubuntu-latest
    strategy:
        matrix:
          test: [ {contract: Invariants, config: assertion}, {contract: Invariants, config: property}, {contract: Crytic, config: crytic}, {contract: UnitTests, config: unit-tests} ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          cache: "yarn"
          node-version: '16.14.0'

      - name: install packages
        run: yarn

      - name: echidna
        uses: crytic/echidna-action@v2
        with:
          solc-version: 0.8.17
          files: test/invariants/STETHVault${{ matrix.test.contract }}.sol
          contract: STETHVault${{ matrix.test.contract }}
          config: test/invariants/config-${{ matrix.test.config }}.yaml
